### ISSUE TITLE
Week 02/Task06

### ISSUE THREAD

**Issue by KHajili98** [Murad685/PragmatechCsharpProject#2]
Task 06 shertini yeniden oxu, cunki case-statement sirasinda problem var....

**_Evvelce girilen ad soyadin qabaqcadan goturulmush ad soyadla ust-uste dushub dushmediyini yoxlayin,  daha sonra eger result true olarsa age-i yoxlayin....._**

**Comment by muradorucov** [comment]
Week02-Task06 duzəlish edib ,yeniden yukledim.
