### ISSUE TITLE
week 3-task1 

### ISSUE THREAD

**Issue by KHajili98** [Murad685/PragmatechCsharpProject#3]
1. `Console.WriteLine("Eded daxil edin:");` loop icerisinde verilse daha anlasiqli olar istifadeci ucun... 
2. while(condition) - ferqli etmeye cehd ele, mesele sertine uygun olaraq. if ile break edib cixmaga gerek qalmasin

**Comment by muradorucov** [comment]
**Week03-Task01** duzelishleri etdim.
