### ISSUE TITLE
week 3 - task 2

### ISSUE THREAD

**Issue by KHajili98** [Murad685/PragmatechCsharpProject#4]
`int f = 1;  f++;`  ---yanasman kicilene dogru getmelidir yeni 4,3,2,1 gedisiniz qaldi... cliente necenci gedisde oldugu onemli deyil, ne qeder gedisi qaldigi onemlidir

**Comment by muradorucov** [comment]
**Week03-Task02** Teleb etdiniyiniz duzelsihi yerine yetirdim.
